# Identificación del proyecto
sonar.projectKey=sistema-recomendacion-vehiculos
sonar.host.url=http://localhost:9000
sonar.projectName=Sistema Recomendacion Vehiculos CDMX
sonar.projectVersion=1.0

# --- ESTA LÍNEA ES CLAVE PARA TU CASO (SIN GIT) ---
sonar.scm.disabled=true

# Codificación
sonar.sourceEncoding=UTF-8

# --- Dónde buscar el código ---
sonar.sources=.

# --- CONFIGURACIÓN BACKEND (PYTHON) ---
# Archivo que generaremos en el Paso 2
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12

# --- CONFIGURACIÓN FRONTEND (REACT) ---
# Archivo que generaremos en el Paso 3
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# --- EXCLUSIONES (Lo que Sonar debe ignorar para no ensuciar el reporte) ---
# Ignorar carpetas de compilación y librerías
# Exclusiones nucleares
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/venv/**,**/.venv/**,**/__pycache__/**,**/coverage/**,**/*.spec.js,**/*.test.js,**/*.css
sonar.login=sqa_6256aa1ec31a7f485cd283018834f4bad68dc316
